dotfiles:
  theme: gruvbox
  languages:
    - ruby
    - python
    - node
    - go 
    - elixir
  tools:
    - git
    - ag
    - z
    - zsh
    - tmux
    - htop-osx
    - nmap
    - tree
    - wget
    - yarn
  editors:
    - neovim
    - vscode
    - intellij
    - android-studio
    - xcode
  apps:
    - docker
    - iterm2
    - chrome 
    - skype
    - skitch 
    - omnidisksweeper
    - colorpicker-developer
    - gyazo
    - licecap
  fonts:
    - source-code-pro
    - fira-sans
customize:
  path: ~/.df



